using System;
using System.Collections.Generic;
using Oracle.ManagedDataAccess.Client; // Certifique-se de ter esse namespace
// Outras referências necessárias...

public class PokemonGroupedByColorDto
{
    public string Color { get; set; }
    public List<string> Names { get; set; }
}

// CREATE TABLE pokemon_colors (
//     id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
//     color VARCHAR2(50) NOT NULL,
//     names CLOB  -- Utilizamos CLOB para armazenar uma lista de nomes, que pode ser longa.
// );

public class OraclePersistenceService
{
    // Exemplo de string de conexão, ajuste conforme seu ambiente Oracle:
    // Data Source pode ser um TNS, Easy Connect ou outra configuração
    private readonly string _connectionString = "User Id=seuUsuario;Password=suaSenha;Data Source=seuDataSource";

    public void SavePokemonGroups(List<PokemonGroupedByColorDto> pokemonGroups)
    {
        try
        {
            using (var connection = new OracleConnection(_connectionString))
            {
                connection.Open();

                foreach (var group in pokemonGroups)
                {
                    using (var command = connection.CreateCommand())
                    {
                        command.CommandText = "INSERT INTO pokemon_colors (color, names) VALUES (:color, :names)";

                        // Adiciona o parâmetro para a cor
                        var colorParam = new OracleParameter("color", OracleDbType.Varchar2)
                        {
                            Value = group.Color
                        };
                        command.Parameters.Add(colorParam);

                        // Converte a lista de nomes em uma única string (ex: separada por vírgulas)
                        var namesConcatenated = string.Join(", ", group.Names);
                        var namesParam = new OracleParameter("names", OracleDbType.Clob)
                        {
                            Value = namesConcatenated
                        };
                        command.Parameters.Add(namesParam);

                        command.ExecuteNonQuery();
                    }
                }
            }

            Console.WriteLine("Dados salvos com sucesso no Oracle.");
        }
        catch (Exception ex)
        {
            // Aqui você pode implementar um log ou tratamento mais detalhado do erro
            Console.WriteLine($"Erro ao salvar dados no Oracle: {ex.Message}");
        }
    }
}
